### ISSUE TITLE
USUM SOS guide has formatting issues on the site

### ISSUE THREAD

**Issue by ShinySylveon04** [zaksabeast/PokemonRNGGuides#95]
For an example, the below image shows that step 2 is a jumbled mess.

![image](https://user-images.githubusercontent.com/26980015/54315027-30164200-45ab-11e9-8f7d-0f0579626b56.png)

This can be solved by having each sentence on a separate line.

> - If two Pokemon are on the field the delay will be longer and the final input will be hitting A while targeting a Pokemon. 

> - If only one Pokemon is on the field the delay will be shorter and the final input will be hitting A while hovering over Use on the Adrenaline Orb.

[This](https://github.com/zaksabeast/PokemonRNGGuides/blob/master/guides/usum/en/SOS%20RNG%20Guide.md) is the file to be edited. Anyone is welcome to open a Pull Request to fix this guide, and for questions you can either ask here or in the #guide-contribution channel of the discord.

## To-do
- [ ] Fix aforementioned formatting
- [ ] Change what is mentioned below
- [ ] Look for and fix any other formatting issues in the guide

**Comment by ShinySylveon04** [comment]
There are some other things that can changed with this guide.

The mention of needing a CFW 3DS should be changed to be consistent with all guides:

`- A 3DS with CFW (Custom Firmware)
    - https://3ds.hacks.guide/ has instructions for installing CFW`

**Comment by ShinySylveon04** [comment]
Also add a mention that SOS RNG always has 0 NPCs for the main RNG and that a timeline is not needed.

**Comment by zaksabeast** [comment]
I'm closing this since the guides were updated for consistency a long time ago.  If I'm not mistaken, USUM guides were fixed with #80.
